### PR TITLE
Game service communication: information-service

### PR DESCRIPTION
**Pull request by CaoimheCahill**
Adding logic for interacting with information-service.

Added methods to:
- Get all teams through api
- Get all teams through database
- Get all matches through api
- Get all matches after a certain date
- Get result of a certain match

Not tested yet

### CODE REVIEW

**Review by olanhealy — DISMISSED** [review]
LGTM, good work. Is the application.properties file deleted ?

**Comment by CaoimheCahill** [comment]
> > LGTM, good work. Is the application.properties file deleted ?
> 
> Actually the job is failing with not recognising imports and some syntax, maybe have Quick Look at that

Fixed problems. Had to edit parts of pom files so that the services could communicate

**Review by olanhealy — APPROVED** [review]
LGTM approving good work

**Review by callum-4 — APPROVED** [review]
lgtm, good job getting those services linked.

**Pull request merged**
