### PR TITLE
Payment service working while isolated. 

### PR DESCRIPTION
**Pull request by callum-4**
Solved issues with previous branch. 
No longer commiting sensitive info. Should be good to go.

Tested using:
http://localhost:8080/api/payment/process

Body example:
{
"amount": "5000", //amount in cents
"currency": "usd", //currency type
"description": "Payment for order #12345", //description of order
"source": "tok_visa" //payment token
}

Options for test source can be found here:
https://docs.stripe.com/testing?testing-method=tokens#tokens

### CODE REVIEW

**Review by olanhealy — APPROVED** [review]
Looks good to me good work. Again I'll reiterate the java docs as 20% is going for code readability but can be done at later date. Approving

**Review by MarkHarrison03 — APPROVED** [review]
Few small issues with naming and importing stripe service key, but other than that lgtm

**Comment by olanhealy** [comment]
Wondering also any photos of successful REST request being sent?

**Comment by MarkHarrison03** [comment]
> Wondering also any photos of successful REST request being sent?

ive tested it and it worked, 
image

**Pull request merged**
