### PR TITLE
Mharrison allow user to join game

### PR DESCRIPTION
**Pull request by MarkHarrison03**
image
allows user to join game. after calling /{id}/join endpoint, authenticates jwt, takes payment and then joins game. user_game_table (bottom db in image) is updated to record the joining of the game, and  payments (top db in image) is updated to record the payment

### CODE REVIEW

**Review by Whomstt — CHANGES_REQUESTED** [review]
Please fix build error

**Comment by MarkHarrison03** [comment]
> Please fix build error

fixed now :D

**Review by olanhealy — APPROVED** [review]
Good work, approving

**Review by CaoimhinHawk1 — APPROVED** [review]
Good job mark, approving

**Pull request merged**
